version: '3.8'

services:
  mongo:
    image: mongo:latest
    # container_name removed
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - phone-store-network

  backend:
    build: ./backend
    # container_name removed to avoid conflict
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/phone-store
      # Overrides or additional variables not in .env
    depends_on:
      - mongo
    networks:
      - phone-store-network

  frontend:
    build: ./frontend
    # container_name removed
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - phone-store-network

networks:
  phone-store-network:
    driver: bridge

volumes:
  mongo-data:
